### ISSUE TITLE
problem about requirement.txt

### ISSUE THREAD

**Issue by BENLONGLONG2000** [MichalZnalezniak/Contrastive-Hierarchical-Clustering#1]
Hello sir, there seems to be a problem with your requirement.txt, I can't install the version you have in it!

**Comment by MichalZnalezniak** [comment]
Hi, thanks for reaching out with your problem.

I have converted the `requirement.txt` file to `environment.yml`. Changes are here #2, it was also merged into the main.

If you want to install the env, please use the following command:
```
conda env create -f environment.yml
```
If you will face any other issues with the environment please let me know I will gladly help you with it 😄 .

**Comment by BENLONGLONG2000** [comment]
thank you sir!!!!!

**Comment by BENLONGLONG2000** [comment]
Hi sir, It still has some problems
![image](https://github.com/MichalZnalezniak/Contrastive-Hierarchical-Clustering/assets/121702935/4e49bca9-49e8-490c-ab68-ddea707a12a8)

**Comment by MichalZnalezniak** [comment]
Hi, could you please tell me what is your conda version? You can check it with 
```
conda -V
```

**Comment by BENLONGLONG2000** [comment]
conda 4.10.3

**Comment by MichalZnalezniak** [comment]
For this project, I was using conda `23.9.0`, could you try to update the conda? In the default env (base env) run
```
conda update conda
```

Let me know if that helped.

**Comment by BENLONGLONG2000** [comment]
Sorry sir, the problem persists, could you tell me what is necessary to install?

**Comment by MichalZnalezniak** [comment]
Here is step by step environment installation for my GPU:
```
conda create -n chc python=3.7.6
conda activate chc
conda install pytorch==1.7.0 torchvision==0.8.0 pytorch-cuda=11.7 -c pytorch -c nvidia
conda install tensorboard
conda install pandas
conda install -c anaconda scikit-learn
pip install omegaconf
pip install thop
conda install -c conda-forge tqdm
```

**Comment by MichalZnalezniak** [comment]
@BENLONGLONG2000 Please let me know if this resolved your issues 😄.

**Comment by BENLONGLONG2000** [comment]
thank you sir! it works. 
i want to know what is the role of memory_data? 
And if I want to design a customised dataset where all the data is used for training and then all the data is clustered, how should I do it?

**Comment by MichalZnalezniak** [comment]
@BENLONGLONG2000, if you don't mind could you please open a new issue regarding your question 😃? I will be happy to help you with it.

**Comment by MichalZnalezniak** [comment]
I'm closing the issue if you will have any problems with env please re-open.
