### ISSUE TITLE
About customised dataset

### ISSUE THREAD

**Issue by BENLONGLONG2000** [MichalZnalezniak/Contrastive-Hierarchical-Clustering#5]
thank you for your patience.
i want to know what is the role of memory_data?
And if I want to design a customised dataset where all the data is used for training and then all the data is clustered, how should I do it?

**Comment by MichalZnalezniak** [comment]
The role of memory_data is to generate a feature bank for the KNN(K-Nearest Neighbors) algorithm while testing in
 `def test(net, memory_data_loader, test_data_loader, epoch, cfg):`
 https://github.com/MichalZnalezniak/Contrastive-Hierarchical-Clustering/blob/47aac392ee23902acbe0bef1c6b9a1d02cacfa3e/main.py#L71C1-L71C1
 
 Metrics coming from the KNN algorithm are quiet information about the latent space that the SSL model generates.

If you want to add a new dataset the best way would be to modify the `utils.py` script (https://github.com/MichalZnalezniak/Contrastive-Hierarchical-Clustering/blob/main/utils.py)

In the `get_contrastive_dataset` function there is a 3-dataset split (train_data, memory_data, test_data), if you want to set the same data for train, memory, and test you can assign the same dataset to train_data, memory_data, test_data. Hope that makes sense 😄.

**Comment by BENLONGLONG2000** [comment]
Hello Sir! I would like to enquire if I can only use the datasets CIFAR10, CIFAR100, STL10, ImageNet, MNIST, FashionMNIST? When I change ImageNet10 to my own dataset, no matter how I modify it, I always get this error.
![image](https://github.com/MichalZnalezniak/Contrastive-Hierarchical-Clustering/assets/121702935/6717a3eb-f6db-448e-a09e-242cce539f14)

**Comment by MichalZnalezniak** [comment]
If you want to use the ImageNet10 you need to download it from here https://www.image-net.org/download.php.
Here is some more information about the ImageNet class https://pytorch.org/vision/stable/generated/torchvision.datasets.ImageNet.html, this should explain why you are getting this error.

If you want to create your own custom dataset, this should help https://pytorch.org/tutorials/beginner/data_loading_tutorial.html

**Comment by MichalZnalezniak** [comment]
@BENLONGLONG2000 Let me now if this resolves your problems, if so I will close the issue 😄
